<?php
/***************************************
 *** Home Background Slider Extension ***
 ***************************************
 *
 * @copyright   Copyright (c) 2015
 * @company     NetAttingo Technologies
 * @package     Netgo_Slider
 * @author 		Vipin
 * @dev			77vips@gmail.com
 *
 */
 
//check if EXTENSION is Enabled
$isEnabled = Mage::getStoreConfig('netgo_slider/homeslider/enableslider');
$enablejQuery = Mage::getStoreConfig('netgo_slider/homeslider/enablejquery');


 if($isEnabled==1){
	 //get slider configuration values
	 $slideInterval = Mage::getStoreConfig('netgo_slider/othersettings/slideinterval');
	 $slideSpeed = Mage::getStoreConfig('netgo_slider/othersettings/slidespeed');
	 $slideAutoplay = Mage::getStoreConfig('netgo_slider/othersettings/slideautoplay');
	 $slideEffect = Mage::getStoreConfig('netgo_slider/othersettings/slideeffect');
	
	 
	 $slideInterval= ($slideInterval!='')?$slideInterval*1000:5000;
	 $slideSpeed= ($slideSpeed!='')?$slideSpeed:500;
	 $slideAutoplay= ($slideAutoplay!='')?$slideAutoplay:0;
	 $slideEffect= ($slideEffect!='')?$slideEffect:0;
	 
	  $enablejQuery= ($enablejQuery!='')?$enablejQuery:0;
	 
        
?>
<?php if($enablejQuery==1){ ?>
	
	
<?php } ?>

<?php 	if(Mage::getBlockSingleton('page/html_header')->getIsHomePage()) {  
                   $ishomepage=true;
	            } else { 
				    $ishomepage=false; 
				}  			 
                 //create image array		 ?>
	
	<?php   if($ishomepage){  
	
	         //GET SLIDER IMAGES
				$_scollection  = Mage::getModel('netgo_slider/homeslider')->getCollection()->addFieldToFilter('status',array('eq'=>1));	
				$imgarr			=array();
				foreach($_scollection->getData() as $key=>$value){ 
					$imgarr[$key]['image']=$value['image']; 
					$imgarr[$key]['caption']=$value['caption']; 
				 }
			  
			  if(count($imgarr)>0){	 
	?> 
	<script type="text/javascript">
			
			jQuery(function($){
				
				$.supersized({
				
					// Functionality
					slideshow               :   1,			// Slideshow on/off
					autoplay				:<?php echo $slideAutoplay; ?>	,			// Slideshow starts playing automatically
					start_slide             :   1,			// Start slide (0 is random)
					stop_loop				:	0,			// Pauses slideshow on last slide
					random					: 	0,			// Randomize slide order (Ignores start slide)
					slide_interval          :   <?php echo $slideInterval; ?>,		// Length between transitions
					transition              :   <?php echo $slideEffect; ?>, 			// 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
					transition_speed		:	<?php echo $slideSpeed;?>,		// Speed of transition
					new_window				:	1,			// Image links open in new window/tab
					pause_hover             :   0,			// Pause slideshow on hover
					keyboard_nav            :   1,			// Keyboard navigation on/off
					performance				:	1,			// 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
					image_protect			:	1,			// Disables image dragging and right click with Javascript
															   
					// Size & Position						   
					min_width		        :   0,			// Min width allowed (in pixels)
					min_height		        :   0,			// Min height allowed (in pixels)
					vertical_center         :   1,			// Vertically center background
					horizontal_center       :   1,			// Horizontally center background
					fit_always				:	0,			// Image will never exceed browser width or height (Ignores min. dimensions)
					fit_portrait         	:   1,			// Portrait images will not exceed browser height
					fit_landscape			:   0,			// Landscape images will not exceed browser width
															   
					// Components							
					slide_links				:	'blank',	// Individual links for each slide (Options: false, 'num', 'name', 'blank')
					thumb_links				:	1,			// Individual thumb links for each slide
					thumbnail_navigation    :   0,			// Thumbnail navigation
					slides 					:  	[			// Slideshow Images
														
									<?php
 							         $mediapath =str_replace('index.php/','',Mage::getBaseUrl()).'media/homeslider/image';
  
									foreach($imgarr as $key=>$value){ 
									 
									
									?>
										
										{image: '<?php echo $mediapath.$value['image']; ?>',title : '<?php echo $value['caption']; ?>',},
										
								<?php	}
									?>		 				 
												],
												
					// Theme Options			   
					progress_bar			:	1,			// Timer for each slide							
					mouse_scrub				:	0
					
				});
		    });
		    
		</script>
		
			   
		 <?php  }//IF COUNT >0 ENDS
				} //IF HOME PAGE ENDS 
		 ?>
 	
  <?php   if($ishomepage){ ?>
		 <!--Thumbnail Navigation-->
	<div id="prevthumb"></div>
	<div id="nextthumb"></div>
	
	<!--Arrow Navigation-->
	<div class="main-slider-nav">
     <div class="slider-nav">
      <a id="prevslide" class="load-item"></a>
	  <a id="nextslide" class="load-item"></a>
        </div>
         </div>
	
	<div id="thumb-tray" class="load-item">
		<div id="thumb-back"></div>
		<div id="thumb-forward"></div>
	</div>
	
		<div class="caption-main"> 
			<div class="caption-right">
				<div class="caption-right-contant">
					<div id="slidecaption"> </div>
				</div>
			</div>
		</div>
	
	<!--Control Bar-->
	<!--Control Bar
	<div id="controls-wrapper" class="load-item">
		<div id="controls">
			
			<a id="play-button"><img id="pauseplay" src="<?php echo $this->getSkinUrl('css/img/pause.png'); ?>"/></a>
		
			 
			<div id="slidecounter">
				<span class="slidenumber"></span> / <span class="totalslides"></span>
			</div>
			
		 
			<div id="slidecaption"></div>
			
		 
			<a id="tray-button"><img id="tray-arrow" src="<?php echo $this->getSkinUrl('css/img/button-tray-up.png'); ?>"/></a>
			
		 
			<ul id="slide-list"></ul>
			
		</div>
	</div>-->
	
		   <?php } ?> 
 <?php } //IF IS ENABLED  ENDS ?>